Attribute VB_Name = "modAGI_Gantt_Automation"
Option Explicit

'=============================================================
' AGI TR Transport Gantt – Convenience Macros
'
' Workbook structure assumed (generated by v6 script):
' - Sheet: Schedule
'   Row 6  : headers (metadata + day headers)
'   Row 7+ : tasks
'   Start date col = G, Finish date col = H
' - Sheet: Tide_Peaks_MZP (Date in col A, from row 2)
' - Sheet: Assumptions_Refs
'   Named cells:
'     CampaignStart   -> Assumptions_Refs!B4 (date)
'     WeekendShadeOn  -> Assumptions_Refs!B5 (TRUE/FALSE)
'     TodayShadeOn    -> Assumptions_Refs!B6 (TRUE/FALSE)
'=============================================================

Public Sub ShiftCampaignStart()
    Dim wb As Workbook: Set wb = ThisWorkbook
    Dim wsA As Worksheet: Set wsA = wb.Worksheets("Assumptions_Refs")
    Dim wsS As Worksheet: Set wsS = wb.Worksheets("Schedule")
    Dim wsT As Worksheet: Set wsT = wb.Worksheets("Tide_Peaks_MZP")

    Dim oldStart As Date
    oldStart = wsA.Range("CampaignStart").Value

    Dim newVal As Variant
    newVal = Application.InputBox("Enter NEW campaign start date (Excel date or yyyy-mm-dd):", "Shift Schedule", oldStart, Type:=2)
    If newVal = False Then Exit Sub

    Dim newStart As Date
    On Error GoTo BadDate
    newStart = CDate(newVal)
    On Error GoTo 0

    Dim delta As Long
    delta = CLng(newStart - oldStart)
    If delta = 0 Then Exit Sub

    Application.ScreenUpdating = False
    Application.EnableEvents = False

    wsA.Range("CampaignStart").Value = newStart

    '----- Shift task Start/Finish dates -----
    Const HEADER_ROW As Long = 6
    Const FIRST_DATA_ROW As Long = 7
    Const COL_START As Long = 7 'G
    Const COL_FINISH As Long = 8 'H

    Dim lastRow As Long
    lastRow = wsS.Cells(wsS.Rows.Count, 1).End(xlUp).Row

    Dim r As Long
    For r = FIRST_DATA_ROW To lastRow
        If Len(Trim$(wsS.Cells(r, 1).Value)) = 0 Then Exit For

        If IsDate(wsS.Cells(r, COL_START).Value) Then wsS.Cells(r, COL_START).Value = wsS.Cells(r, COL_START).Value + delta
        If IsDate(wsS.Cells(r, COL_FINISH).Value) Then wsS.Cells(r, COL_FINISH).Value = wsS.Cells(r, COL_FINISH).Value + delta

        ' Baseline columns (K/L) if used
        If IsDate(wsS.Cells(r, 11).Value) Then wsS.Cells(r, 11).Value = wsS.Cells(r, 11).Value + delta
        If IsDate(wsS.Cells(r, 12).Value) Then wsS.Cells(r, 12).Value = wsS.Cells(r, 12).Value + delta
    Next r

    '----- Shift timeline header dates (row 6, from first day column to end) -----
    Dim firstDayCol As Long
    firstDayCol = 17 'Q (after 16 meta columns)

    Dim lastCol As Long
    lastCol = wsS.Cells(HEADER_ROW, wsS.Columns.Count).End(xlToLeft).Column

    Dim c As Long
    For c = firstDayCol To lastCol
        If IsDate(wsS.Cells(HEADER_ROW, c).Value) Then
            wsS.Cells(HEADER_ROW, c).Value = wsS.Cells(HEADER_ROW, c).Value + delta
        End If
    Next c

    '----- Shift tide peaks dates -----
    Dim tr As Long
    tr = 2
    Do While IsDate(wsT.Cells(tr, 1).Value)
        wsT.Cells(tr, 1).Value = wsT.Cells(tr, 1).Value + delta
        tr = tr + 1
    Loop

    wb.RefreshAll
    wb.Application.CalculateFull

CleanExit:
    Application.EnableEvents = True
    Application.ScreenUpdating = True
    Exit Sub

BadDate:
    MsgBox "Invalid date. Please enter an Excel-recognizable date (e.g., 2026-01-13).", vbExclamation
    Resume CleanExit
End Sub


Public Sub ToggleWeekendShading()
    Dim wsA As Worksheet: Set wsA = ThisWorkbook.Worksheets("Assumptions_Refs")
    wsA.Range("WeekendShadeOn").Value = Not CBool(wsA.Range("WeekendShadeOn").Value)
    ThisWorkbook.Calculate
End Sub


Public Sub ToggleTodayShading()
    Dim wsA As Worksheet: Set wsA = ThisWorkbook.Worksheets("Assumptions_Refs")
    wsA.Range("TodayShadeOn").Value = Not CBool(wsA.Range("TodayShadeOn").Value)
    ThisWorkbook.Calculate
End Sub


Public Sub ExportScheduleAndChartPDF()
    Dim fn As Variant
    fn = Application.GetSaveAsFilename(InitialFileName:="AGI_TR_Gantt.pdf", FileFilter:="PDF Files (*.pdf), *.pdf")
    If fn = False Then Exit Sub

    Application.ScreenUpdating = False
    Application.EnableEvents = False

    Sheets(Array("Schedule", "Gantt_Chart")).Select
    ActiveSheet.ExportAsFixedFormat Type:=xlTypePDF, Filename:=CStr(fn), Quality:=xlQualityStandard, IncludeDocProperties:=True, IgnorePrintAreas:=False, OpenAfterPublish:=True

    Sheets("Schedule").Select

    Application.EnableEvents = True
    Application.ScreenUpdating = True
End Sub


Public Sub ResetScheduleFilters()
    On Error GoTo SafeExit

    Dim wsS As Worksheet: Set wsS = ThisWorkbook.Worksheets("Schedule")

    If wsS.AutoFilterMode Then
        If wsS.FilterMode Then wsS.ShowAllData
    End If

SafeExit:
End Sub
